/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test4;

public class Library {
	
	public static void main(String arg[]) {
		
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
