/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class Library {
	public static void main(String arg[]) {
		System.out.print("hello world");
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
    //change project location
}

//submit something from windows 10 //
